# destroy.yml
---
- name: Destroy Proxy Instances
  hosts: tag_proxies
  gather_facts: false
  tasks:
    - name: Delete instance
      linode.cloud.instance:
        api_token: "{{ lookup('env', 'LINODE_TOKEN') }}"
        label: "{{ inventory_hostname }}"
        state: absent
      delegate_to: localhost

    - name: Remove DNS record
      linode.cloud.domain_record:
        api_token: "{{ lookup('env', 'LINODE_TOKEN') }}"
        domain: "{{ proxy_domain.split('.')[-2:] | join('.') }}"
        type: "A"
        name: "{{ proxy_domain.split('.')[0] }}"
        state: absent
      delegate_to: localhost
      