# Obscures the ssh port - more to stop endless door knocking
# filling up logs than to significantly improve ssh security
---
- name: Wait for SSH port
  hosts: tag_needs_ssh_config
  gather_facts: false
  tasks:
    - name: Wait for default SSH port
      delegate_to: localhost
      wait_for:
        delay: 1
        port: 22
        timeout: 180
        state: started
        host: "{{ ansible_host }}"

- name: Change SSH Server Port
  hosts: tag_needs_ssh_config
  gather_facts: false
  tasks:
    - name: Configure SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port '
        line: "Port {{ ssh_port }}"
        validate: '/usr/sbin/sshd -t -f %s'

    - name: 'Initiate Reboot without waiting - forces updated ssh to be used'
      shell: 'sleep 1 && reboot -f && sleep 1'
      async: 1
      poll: 0

    - name: Remove needs_ssh_config tag
      delegate_to: localhost
      linode.cloud.instance:
        api_token: "{{ lookup('env', 'LINODE_API_TOKEN') }}"
        label: "{{ instance_name }}"
        tags: ["proxies"]
        state: present

