---
- name: Update Server Instance Playbook
  hosts: tag_proxies
  gather_facts: false
  become: true
  become_user: root
  roles:
    - { role: base,     tags: [ 'base' ] }
    - { role: security, tags: [ 'security' ] }
    - { role: proxy,    tags: [ 'proxy' ] }
    - { role: web,      tags: [ 'web' ] }
    - { role: oauth2_proxy, tags: [ 'oauth2' ] }
    - { role: optimize, tags: [ 'optimize' ] }
    - { role: reboot,   tags: [ 'reboot' ] }
