---
- name: Set up systemd service
  template:
    src: api.service.j2
    dest: /etc/systemd/system/plannies-api.service
  notify: restart api

- name: Enable and start API service
  systemd:
    name: plannies-api
    enabled: yes
    state: started
    daemon_reload: yes
