---
- name: Install Ruby and dependencies
  apt:
    name:
      - ruby
      - ruby-dev
      - build-essential
    state: present
    update_cache: yes

- name: Install required gems
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
    bindir: /usr/local/bin
  loop:
    - bundler
