---
- name: Ensure local html directory exists
  file:
    path: "{{ playbook_dir }}/tmp/html/"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false
  tags: 'website'

- name: Copy static website files to remote server
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/var/www/html/"
    owner: caddy
    group: caddy
    mode: '0644'
    directory_mode: '0755'
  tags: 'website'
  loop: "{{ web_static_assets }}"

- name: Copy static website files to local html directory
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ playbook_dir }}/tmp/html/"
    mode: '0644'
    directory_mode: '0755'
  delegate_to: localhost
  become: false
  tags: 'website'
  loop: "{{ web_static_assets }}"

- name: Build themed files
  command: bin/build_theme
  delegate_to: localhost
  register: build_result
  tags: 'website'
  become: false
  changed_when: "'Generated' in build_result.stdout"

- name: Copy built website files to remote server
  copy:
    src: "{{ playbook_dir }}/tmp/build/"
    dest: /var/www/html/
    owner: caddy
    group: caddy
    mode: '0644'
    directory_mode: '0755'
  tags:
    - 'website'
    - 'themed'

- name: Copy built website files to local html directory
  copy:
    src: "{{ playbook_dir }}/tmp/build/"
    dest: "{{ playbook_dir }}/tmp/html/"
    mode: '0644'
    directory_mode: '0755'
  delegate_to: localhost
  become: false
  tags:
    - 'website'
    - 'themed'
