#
---
- name: Fetch Cloudflare IPv4 ranges
  uri:
    url: https://www.cloudflare.com/ips-v4
    return_content: yes
  tags:
    - 'website'
    - 'cloudflare'
  register: cf_ipv4

- name: Fetch Cloudflare IPv6 ranges
  uri:
    url: https://www.cloudflare.com/ips-v6
    return_content: yes
  tags:
    - 'website'
    - 'cloudflare'
  register: cf_ipv6

- name: Configure Caddy
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: '0644'
  tags:
    - 'website'
    - 'users'
    - 'cloudflare'
  notify: restart caddy
